[package]
authors = ["Matthias <matthias.seitz@tum.de>"]
name = "rust-ads"
version = "0.1.0"

[dependencies]
bincode = "0.9.2"
byteorder = "1.2.1"
bytes = "0.4.5"
serde = "1.0.23"
serde_derive = "1.0.23"
